{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DirectQuery to AS - LW_Weather_Analysis\",\"external_table('csv_meteo_data_canada')\",\"DirectQuery to AS - LW_Weather_Analysis 2\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.126.927.0 (24.02)"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "DirectQuery to AS - LW_Weather_Analysis",
        "annotations": [
          {
            "name": "PBI_IncludeFutureArtifacts",
            "value": "True"
          }
        ],
        "expression": [
          "let",
          "    Source = AnalysisServices.Database(\"powerbi://api.powerbi.com/v1.0/myorg/Eyes on future (Eng)\", \"LW_Weather_Analysis\"),",
          "    Cubes = Table.Combine(Source[Data]),",
          "    Cube = Cubes{[Id=\"d51dcaf5-4c41-46f3-87dd-9744a5796a93\", Kind=\"Cube\"]}[Data]",
          "in",
          "    Cube"
        ],
        "kind": "m",
        "lineageTag": "910664a0-06f7-4bf3-94f5-057f0bc0103a"
      },
      {
        "name": "DirectQuery to AS - LW_Weather_Analysis 2",
        "annotations": [
          {
            "name": "PBI_IncludeFutureArtifacts",
            "value": "True"
          },
          {
            "name": "PBI_RemovedChildren",
            "value": "[{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"a5c64bdc-f50b-4d77-915c-ca8668f57e0f\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"77d31481-c947-489a-8ca9-e91ac664edec\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"d644f107-1525-43a2-9c50-c983ebdc39bb\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"facf8611-aa06-41be-953e-e915afd3a242\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"94661eae-4e56-4d43-a61e-3228e06107c4\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"fa44837f-3176-40cb-9aff-8b683126b727\"}},\"objectType\":\"Table\"}]"
          }
        ],
        "expression": [
          "let",
          "    Source = AnalysisServices.Database(\"powerbi://api.powerbi.com/v1.0/myorg/Eyes%20on%20future%20%28Eng%29\", \"LW_Weather_Analysis\"),",
          "    Cubes = Table.Combine(Source[Data]),",
          "    Cube = Cubes{[Id=\"d51dcaf5-4c41-46f3-87dd-9744a5796a93\", Kind=\"Cube\"]}[Data]",
          "in",
          "    Cube"
        ],
        "kind": "m",
        "lineageTag": "0f326649-b18e-4e02-a7a5-e695bfd1f7cc"
      }
    ],
    "relationships": [
      {
        "name": "bdb778fc-fb71-40b4-8431-c8c0d72a7634",
        "fromColumn": "date",
        "fromTable": "WeatherForcast",
        "toColumn": "date",
        "toTable": "Date"
      },
      {
        "name": "079f06a3-b1dd-45af-bc5a-e40924f44edf",
        "fromColumn": "ClimateID",
        "fromTable": "WeatherForcast",
        "toColumn": "ClimateID",
        "toTable": "Station"
      },
      {
        "name": "e81ef418-5be6-4cb3-9569-3dc72320a814",
        "fromColumn": "Datetime",
        "fromTable": "WeatherHistory",
        "toColumn": "date",
        "toTable": "Date"
      },
      {
        "name": "5067ab42-3d89-4cdc-babb-06eba4b71d1b",
        "fromColumn": "ClimateID",
        "fromTable": "WeatherHistory",
        "toColumn": "ClimateID",
        "toTable": "Station"
      },
      {
        "name": "fa740a8a-9874-4574-ac0a-8f54a17c08ec",
        "fromColumn": "Date",
        "fromTable": "Weatherlive",
        "toColumn": "date",
        "toTable": "Date"
      },
      {
        "name": "fad1df30-6dd4-4c4a-aef5-803cb2831c8c",
        "fromColumn": "ClimateID",
        "fromTable": "Weatherlive",
        "toColumn": "ClimateID",
        "toTable": "Station"
      },
      {
        "name": "fa6b245a-5691-4e4e-8f89-f992a637e5f6",
        "fromColumn": "Station",
        "fromTable": "external_table('csv_meteo_data_canada')",
        "securityFilteringBehavior": "none",
        "toCardinality": "many",
        "toColumn": "Name",
        "toTable": "Station"
      },
      {
        "name": "81084bc9-1899-4d50-83bb-7b84c2ef9cfa",
        "fromColumn": "Date",
        "fromTable": "external_table('csv_meteo_data_canada')",
        "securityFilteringBehavior": "none",
        "toColumn": "date",
        "toTable": "Date"
      }
    ],
    "sourceQueryCulture": "fr-CA",
    "tables": [
      {
        "name": "WeatherForcast",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "04714f58-0f39-4c5e-8d13-308acaaa52ad",
            "sourceColumn": "date",
            "sourceLineageTag": "b108a59f-8e65-45a9-811f-4301c7335cea",
            "summarizeBy": "none"
          },
          {
            "name": "Rain_predicted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "9ac96bcb-fbf0-480c-b1d2-e3c5a35760c9",
            "sourceColumn": "Rain_predicted",
            "sourceLineageTag": "383b6b97-d558-4645-b8e4-878254b4c1a0",
            "summarizeBy": "sum"
          },
          {
            "name": "MaxTempC_predicted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "e96dc4d1-67f6-4378-87c0-62d5d48bffb9",
            "sourceColumn": "MaxTempC_predicted",
            "sourceLineageTag": "ac06e4bf-3d37-4596-9e70-2a600f97083f",
            "summarizeBy": "sum"
          },
          {
            "name": "MinTempC_predicted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "62740233-9007-4845-ae2e-2fcea7460a6c",
            "sourceColumn": "MinTempC_predicted",
            "sourceLineageTag": "76d5a240-0088-41fe-8ba9-1101df32b9bd",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalPrecipmm_predicted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "50321a4f-592f-4251-a711-7a7d753500ef",
            "sourceColumn": "TotalPrecipmm_predicted",
            "sourceLineageTag": "0f706ac9-109e-40b2-b86f-f46dfeb699eb",
            "summarizeBy": "sum"
          },
          {
            "name": "Precipitation_predicted_fbp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "434be429-dd2e-416f-be60-69de18f8c35a",
            "sourceColumn": "Precipitation_predicted_fbp",
            "sourceLineageTag": "f2223c2a-ad2b-44cd-9f1c-8df792e8b32b",
            "summarizeBy": "sum"
          },
          {
            "name": "ClimateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "1f46f7df-5571-4fcc-82da-f358a862591b",
            "sourceColumn": "ClimateID",
            "sourceLineageTag": "743367d5-33f7-48ef-a97e-9a8ee0bea290",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5286a912-5648-44fe-bbf6-8bf99bde2168",
        "partitions": [
          {
            "name": "WeatherForcast",
            "mode": "directQuery",
            "source": {
              "entityName": "WeatherForcast",
              "expressionSource": "DirectQuery to AS - LW_Weather_Analysis",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "a5c64bdc-f50b-4d77-915c-ca8668f57e0f"
      },
      {
        "name": "WeatherHistory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "ClimateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "862a10b6-1db7-42cf-a3cb-90ed5b05bece",
            "sourceColumn": "ClimateID",
            "sourceLineageTag": "9e5bf43d-2354-4447-9108-461a304b6022",
            "summarizeBy": "none"
          },
          {
            "name": "Datetime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "e254fc90-1fdf-4771-b4f7-9c84a6e6d706",
            "sourceColumn": "Datetime",
            "sourceLineageTag": "67a0498e-1c6e-426f-b566-0f2c58c353d0",
            "summarizeBy": "none"
          },
          {
            "name": "MaxTempC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "503d36b4-4a44-4687-9b15-8cf5920acf06",
            "sourceColumn": "MaxTempC",
            "sourceLineageTag": "cca34c30-fba2-42e3-8f50-4460083879f6",
            "summarizeBy": "sum"
          },
          {
            "name": "MinTempC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "0a84b744-2d49-4214-9308-d9d8c487adcc",
            "sourceColumn": "MinTempC",
            "sourceLineageTag": "2c224f48-170e-4bc2-b42b-c6a44e02b5de",
            "summarizeBy": "sum"
          },
          {
            "name": "MeanTempC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "694a94a9-db6f-4fed-a4dd-d621dc5dbf35",
            "sourceColumn": "MeanTempC",
            "sourceLineageTag": "80e37cde-b6c3-4004-92f9-6e189d9c72c6",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalPrecipmm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "1df8ffe2-526b-44e1-996e-963b22bcc1b4",
            "sourceColumn": "TotalPrecipmm",
            "sourceLineageTag": "8da00830-0fa8-4b1a-ab41-c7cc10d7eb1d",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6a29b272-88a6-4b0e-a010-45c3c39dd984",
        "partitions": [
          {
            "name": "WeatherHistory",
            "mode": "directQuery",
            "source": {
              "entityName": "WeatherHistory",
              "expressionSource": "DirectQuery to AS - LW_Weather_Analysis",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "77d31481-c947-489a-8ca9-e91ac664edec"
      },
      {
        "name": "Weatherlive",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "ClimateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "530a9f66-7f3a-4eec-bc6a-ecdbc4f7ad9a",
            "sourceColumn": "ClimateID",
            "sourceLineageTag": "45cce998-985c-4c05-85ee-370f94785831",
            "summarizeBy": "none"
          },
          {
            "name": "Temperature",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "72de9860-a1ba-4b9d-a932-fd10306225ef",
            "sourceColumn": "Temperature",
            "sourceLineageTag": "b03dc8b7-a6ba-4d7e-aea3-4cd5557c3343",
            "summarizeBy": "sum"
          },
          {
            "name": "TemperatureMin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "7db24381-e1ae-48ad-bf56-31e6f10dc849",
            "sourceColumn": "TemperatureMin",
            "sourceLineageTag": "114c6e1b-d53a-4dff-8648-d59f9efd9fb9",
            "summarizeBy": "sum"
          },
          {
            "name": "TemperatureMax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "9a885c63-5680-478c-b670-a020750001c3",
            "sourceColumn": "TemperatureMax",
            "sourceLineageTag": "eda01b1f-a810-4315-b42c-242434a63403",
            "summarizeBy": "sum"
          },
          {
            "name": "Humidity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ffb5cb93-90fc-43f8-865a-682d294242dc",
            "sourceColumn": "Humidity",
            "sourceLineageTag": "410f889b-d9b4-4a9f-810e-06fa61d5ca40",
            "summarizeBy": "sum"
          },
          {
            "name": "Pressure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0333a9a9-6504-4cf2-8020-51ce7eabcc46",
            "sourceColumn": "Pressure",
            "sourceLineageTag": "6ba35f56-b82c-4e3e-8662-493eeca7f094",
            "summarizeBy": "sum"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "1e3601d6-3fff-406b-beaf-6711086ef848",
            "sourceColumn": "Description",
            "sourceLineageTag": "e6083381-eeaf-48e1-9900-b51dfddc2f8e",
            "summarizeBy": "none"
          },
          {
            "name": "Rain",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "double",
            "lineageTag": "6780f4d7-3e8c-4aca-ad56-cb4ea86d80a4",
            "sourceColumn": "Rain",
            "sourceLineageTag": "5913c4df-e76a-4bce-833e-e5ac01669e08",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "a76d83f5-17e8-4477-be0e-1c3329e3e87a",
            "sourceColumn": "Date",
            "sourceLineageTag": "81d97019-ebbd-4d96-ae4d-b1c87d5c9dcf",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "693fb9a4-6b90-4bf5-8dfb-dbb96c514bb1",
        "partitions": [
          {
            "name": "Weatherlive",
            "mode": "directQuery",
            "source": {
              "entityName": "Weatherlive",
              "expressionSource": "DirectQuery to AS - LW_Weather_Analysis",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "d644f107-1525-43a2-9c50-c983ebdc39bb"
      },
      {
        "name": "Station",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "ClimateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "bb67688d-5387-476e-83c8-48e900cfcd3d",
            "sourceColumn": "ClimateID",
            "sourceLineageTag": "e194db2a-14d8-49e6-b43d-0eec12d1d5f3",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "107d652a-b0fa-4c11-8ba1-32e0bb544205",
            "sourceColumn": "Name",
            "sourceLineageTag": "f0758c7c-f48e-49bc-8618-0892bd7d8791",
            "summarizeBy": "none"
          },
          {
            "name": "Province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "00c95d43-6214-4777-be21-32e66fb0b508",
            "sourceColumn": "Province",
            "sourceLineageTag": "c290b3c5-2713-4c97-a97e-53d87171cd8b",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6eaaec40-6046-4ea3-824f-e380f1717805",
        "partitions": [
          {
            "name": "Station",
            "mode": "directQuery",
            "source": {
              "entityName": "Station",
              "expressionSource": "DirectQuery to AS - LW_Weather_Analysis",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "facf8611-aa06-41be-953e-e915afd3a242"
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "isNullable": false,
            "lineageTag": "62941d9d-1c45-40e6-b944-ae41f1ad463d",
            "sourceColumn": "date",
            "sourceLineageTag": "77e55efd-1a62-40e5-9a6c-f8423cbbfbd5",
            "summarizeBy": "none"
          },
          {
            "name": "year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bf5cba82-cab3-4edb-9357-b2dd76d1a871",
            "sourceColumn": "year",
            "sourceLineageTag": "b020f1ed-b47d-404d-95f6-5c698d053725",
            "summarizeBy": "sum"
          },
          {
            "name": "month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2804fae5-f8a1-482f-b154-0551f7de4bb4",
            "sourceColumn": "month",
            "sourceLineageTag": "6ceedbe6-65c2-41ab-922d-eb4d53108389",
            "summarizeBy": "sum"
          },
          {
            "name": "day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0ce3e43a-015d-4ebd-81cb-1313e9cfc285",
            "sourceColumn": "day",
            "sourceLineageTag": "a64bff15-07bc-46b0-8a76-ecd41096b0a4",
            "summarizeBy": "sum"
          },
          {
            "name": "season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "5f1d111f-c768-4aa3-ba6c-f9b99f1f5e35",
            "sourceColumn": "season",
            "sourceLineageTag": "c3fd9c87-e2f9-43e8-b5da-627ab3019fbf",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "314e48a9-63e9-42b9-b0aa-c6162908d736",
        "measures": [
          {
            "name": "axisY_SelectedMetric_Real_MaximalValue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var result=",
              "CALCULATE(",
              "    [SelectedMetric_Real],",
              "    ALLSELECTED('Date'[date])",
              "    ) ",
              "RETURN   result"
            ],
            "lineageTag": "8c0ef12f-2bd1-4893-8ba0-96699f0006f9"
          },
          {
            "name": "axisYSelectedMetric_Forecast_MaximalValue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var result=",
              "CALCULATE(",
              "    [SelectedMetric_Forecast],",
              "    FILTER(ALLSELECTED('Date'[date]), 'Date'[date]>[MaxRealDate])",
              "    ) ",
              "RETURN result",
              ""
            ],
            "lineageTag": "f10842fd-8cc0-4dfc-830a-12323e34a087"
          },
          {
            "name": "textday",
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": [
              "",
              " var daynbr=count('Date'[day])",
              " RETURN",
              " CONCATENATE(\"This will cover period of : \",count('Date'[day])) & if(daynbr>1,\"days\",\"day\")"
            ],
            "lineageTag": "d3e0ed1d-d362-4714-9160-a5012779a34a"
          },
          {
            "name": "anomalies",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "DataCategory"
              }
            ],
            "dataCategory": "ImageUrl",
            "expression": "\"data:application/octet-stream;base64,iVBORw0KGgoAAAANSUhEUgAAAeAAAADwCAYAAADYdbe6AAAgAElEQVR4nO2dCZwk\"",
            "lineageTag": "9f32d911-2355-440d-b85a-8e883fe704c6"
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "directQuery",
            "source": {
              "entityName": "Date",
              "expressionSource": "DirectQuery to AS - LW_Weather_Analysis",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "94661eae-4e56-4d43-a61e-3228e06107c4"
      },
      {
        "name": "Metric_Param",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aad2c327-5dfe-494c-bf0e-c702d5698a96",
            "sourceColumn": "id",
            "sourceLineageTag": "7770df88-8913-47e9-947d-11f1e738095c",
            "summarizeBy": "sum"
          },
          {
            "name": "Metric",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "c187c1b6-aa70-4170-a0f2-1a74b3e7cacf",
            "sourceColumn": "Metric",
            "sourceLineageTag": "862de167-aac0-4793-8f8c-d2a6c32cc1d0",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "41e055de-7bbd-4aef-b228-c6095ce8cb12",
        "measures": [
          {
            "name": "SelectedMetric_Real",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"SelectedMetric_Real\", DOUBLE, \"DirectQuery to AS - LW_Weather_Analysis\")",
            "lineageTag": "ef2b9869-a188-49a0-a0bc-576547e73464",
            "sourceLineageTag": "265c9ad0-63b4-426a-8815-636940765d43"
          },
          {
            "name": "SelectedMetric_Forecast",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"SelectedMetric_Forecast\", DOUBLE, \"DirectQuery to AS - LW_Weather_Analysis\")",
            "lineageTag": "b042632a-abaf-47c3-9853-0dabdc83d240",
            "sourceLineageTag": "a73bd02f-7b78-4db4-9d4a-5a1398976379"
          },
          {
            "name": "SelectedMetric_Forecast_NotFIltred",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"SelectedMetric_Forecast_NotFIltred\", DOUBLE, \"DirectQuery to AS - LW_Weather_Analysis\")",
            "lineageTag": "8fd0e0e8-6b1b-4682-8f84-b65efb353d4e",
            "sourceLineageTag": "32569a55-6873-4d80-9074-ad3c679b8bf4"
          },
          {
            "name": "SelectedMetric_Forecast_MaximalValue",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"SelectedMetric_Forecast_MaximalValue\", STRING, \"DirectQuery to AS - LW_Weather_Analysis\")",
            "lineageTag": "e9d46bf3-f04b-4037-a374-f1dd274a4e58",
            "sourceLineageTag": "9f9257c9-6ddf-4ff4-b762-cead229d5633"
          },
          {
            "name": "today",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"today\", DATETIME, \"DirectQuery to AS - LW_Weather_Analysis\")",
            "formatString": "General Number",
            "lineageTag": "247aa228-e20a-43b2-880f-576061484111",
            "sourceLineageTag": "0c56c348-fcc7-487f-aa55-89228d80cc2f"
          },
          {
            "name": "MeanTempReal",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"MeanTempReal\", DOUBLE, \"DirectQuery to AS - LW_Weather_Analysis\")",
            "lineageTag": "483248ea-22f0-44c5-a936-29ff540d6a97",
            "sourceLineageTag": "b902f985-ac47-4b96-8b16-3c4fc55d53f3"
          },
          {
            "name": "MeanRainReal",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"MeanRainReal\", DOUBLE, \"DirectQuery to AS - LW_Weather_Analysis\")",
            "lineageTag": "67432206-110c-4c75-92dd-be2313f19c96",
            "sourceLineageTag": "05a75997-bf35-4f4e-b510-1e8004fb83ba"
          },
          {
            "name": "RainReal",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"RainReal\", DOUBLE, \"DirectQuery to AS - LW_Weather_Analysis\")",
            "lineageTag": "72278e64-fbba-47fa-843d-d89408c7498a",
            "sourceLineageTag": "43e50259-33df-45ae-bdfd-f8c622973786"
          },
          {
            "name": "SelectedMetric_Real_MaximalValue",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"SelectedMetric_Real_MaximalValue\", STRING, \"DirectQuery to AS - LW_Weather_Analysis\")",
            "lineageTag": "a404c03e-7a97-485f-a8af-51c753b359a3",
            "sourceLineageTag": "7113a57f-d2c1-4b36-9fda-357f0a86b944"
          },
          {
            "name": "MaxRealDate",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"MaxRealDate\", DATETIME, \"DirectQuery to AS - LW_Weather_Analysis\")",
            "formatString": "General Number",
            "lineageTag": "7dbfe7ba-8872-4020-b7ec-f929cb5d556e",
            "sourceLineageTag": "8832d613-34cc-4019-b03d-8726d73f76ee"
          },
          {
            "name": "SelectedMetric_Forecast_MaximalValue_Error",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"SelectedMetric_Forecast_MaximalValue_Error\", DOUBLE, \"DirectQuery to AS - LW_Weather_Analysis\")",
            "lineageTag": "a44e1991-8718-460a-8982-e15b541c80ff",
            "sourceLineageTag": "b5eac729-dd5c-4ad4-af11-ee50b86255ee"
          },
          {
            "name": "displayIcone",
            "expression": [
              "",
              " SWITCH(",
              "    SELECTEDVALUE(Metric_Param[id]),",
              "    1,[fireIcone],",
              "    2,[iceIcone],",
              "    3,[rainIcone]",
              " )"
            ],
            "lineageTag": "34efd59f-7524-4e68-a812-96b9cc1ea179"
          },
          {
            "name": "fireIcone",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA1wAAAQLCAYAAACfyagFAACAAElEQVR42uydh3dc\""
            ],
            "lineageTag": "e7d9d881-3072-4048-8850-25c0947f0bcd"
          },
          {
            "name": "iceIcone",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AACEuklEQVR42u2dCXjc\""
            ],
            "lineageTag": "7a6da07f-becd-48e5-a5d3-977fc265f652"
          },
          {
            "name": "rainIcone",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "\"",
              "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AABoVklEQVR42u2dCXgT",
              "\""
            ],
            "lineageTag": "5e15f9d4-f09c-4fa9-9226-1b3ef89d7b64"
          },
          {
            "name": "debug",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(MAX(WeatherHistory[Datetime]),ALL(WeatherHistory))",
            "lineageTag": "482b0adb-1d4d-4941-bf59-94dd29443147"
          },
          {
            "name": "titletimeseries",
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "SELECTEDVALUE(Metric_Param[Metric])& \" Real and Forecast by date\"",
            "lineageTag": "0c7f0264-8c87-44d6-a77d-d78f0d631da1"
          }
        ],
        "partitions": [
          {
            "name": "Metric_Param",
            "mode": "directQuery",
            "source": {
              "entityName": "Metric_Param",
              "expressionSource": "DirectQuery to AS - LW_Weather_Analysis",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "fa44837f-3176-40cb-9aff-8b683126b727"
      },
      {
        "name": "external_table('csv_meteo_data_canada')",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4d2d40bf-f7f9-4ffc-bd5d-00a9c612c277",
            "sourceColumn": "Date",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "Max Temp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "62f63873-69d9-4d92-a8c5-bec0746a547d",
            "sourceColumn": "Max Temp",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Min Temp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cf6026f1-67dc-4cbd-81a5-5ffea5c0fe8d",
            "sourceColumn": "Min Temp",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Heat Deg Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6a4fcfa7-c9d9-4d33-a23f-c4292a87afca",
            "sourceColumn": "Heat Deg Days",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Precip (mm)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d1146ca5-ebeb-43e9-9806-fb33270c4fd4",
            "sourceColumn": "Total Precip (mm)",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Station",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74a214d7-a486-40df-80d4-e0abb77c22a5",
            "sourceColumn": "Station",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1400d847-cf1c-4a79-80b3-ca2a55ab5bae",
        "partitions": [
          {
            "name": "external_table('csv_meteo_data_canada')",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = AzureDataExplorer.Contents(\"https://trd-uh5qsaha2jcsv3zrmv.z9.kusto.fabric.microsoft.com\", \"KQL_DB_live_weather\"),",
                "    #\"external_table('csv_meteo_data_canada')1\" = Source{[Name=\"external_table('csv_meteo_data_canada')\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"external_table('csv_meteo_data_canada')1\",{{\"_c0\", \"Longitude (x)\"}, {\"_c1\", \"Latitude (y)\"}, {\"_c4\", \"Date\"}, {\"_c9\", \"Max Temp\"}, {\"_c11\", \"Min Temp\"}, {\"_c15\", \"Heat Deg Days\"}, {\"_c23\", \"Total Precip (mm)\"}, {\"_c25\", \"_c25\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each ( [#\"Total Precip (mm)\"] <> \"Total Precip (mm)\")),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows\",{\"_c2\", \"Date\", \"Max Temp\", \"Min Temp\", \"Heat Deg Days\", \"Total Precip (mm)\"}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Other Columns\", each true),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows1\",{{\"Max Temp\", type number}, {\"Min Temp\", type number}, {\"Heat Deg Days\", type number}, {\"Total Precip (mm)\", type number}, {\"Date\", type date}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type\",{{\"_c2\", \"Station\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "weather_anomalies_analysis",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "currentTemp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"fr-CA\"}"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \\$;(#,0.###############\\ \\$);#,0.###############\\ \\$",
            "lineageTag": "4b7f7e5e-73b0-4414-8fc1-431316b867e5",
            "sourceColumn": "currentTemp",
            "sourceLineageTag": "ffed0d64-41a4-4878-aae8-72f23e04df95",
            "summarizeBy": "sum"
          },
          {
            "name": "analyisGPT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "da65160f-02d1-44bd-8d9b-2302b3d46702",
            "sourceColumn": "analyisGPT",
            "sourceLineageTag": "e4e98279-033c-4f19-88af-1053eb2ecf57",
            "summarizeBy": "none"
          },
          {
            "name": "Datetime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "721c1b75-37c8-4d02-9646-9f1b14d37594",
            "sourceColumn": "Datetime",
            "sourceLineageTag": "813a5f48-c56b-4bec-a9bc-bdd3d1fe50b3",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c6cffea2-63db-41aa-91c1-33efd46d4fbe",
        "partitions": [
          {
            "name": "weather_anomalies_analysis",
            "mode": "directQuery",
            "source": {
              "entityName": "weather_anomalies_analysis",
              "expressionSource": "DirectQuery to AS - LW_Weather_Analysis 2",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "4420353f-1f2c-4ead-89fd-d04d1fab6e98"
      }
    ]
  }
}